spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=movies;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true